// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZaPutevkoi.API.data;

#nullable disable

namespace ZaPutevkoi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328100421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZaPutevkoi.API.Entities.AccommodationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelFiltersEntityId")
                        .HasColumnType("int");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelFiltersEntityId")
                        .IsUnique();

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.AvailabilityPeriodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelFiltersEntityId")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelFiltersEntityId");

                    b.ToTable("AvailabilityPeriods");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("RatingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelFiltersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelEntityId")
                        .HasColumnType("int");

                    b.Property<string>("MealPlansJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelEntityId")
                        .IsUnique();

                    b.ToTable("HotelFilters");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelEntityId");

                    b.ToTable("HotelImages");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelSectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelEntityId")
                        .HasColumnType("int");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelEntityId");

                    b.ToTable("HotelSections");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.AccommodationEntity", b =>
                {
                    b.HasOne("ZaPutevkoi.API.Entities.HotelFiltersEntity", "HotelFilters")
                        .WithOne("Accommodation")
                        .HasForeignKey("ZaPutevkoi.API.Entities.AccommodationEntity", "HotelFiltersEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelFilters");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.AvailabilityPeriodEntity", b =>
                {
                    b.HasOne("ZaPutevkoi.API.Entities.HotelFiltersEntity", "HotelFilters")
                        .WithMany("Availability")
                        .HasForeignKey("HotelFiltersEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelFilters");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelFiltersEntity", b =>
                {
                    b.HasOne("ZaPutevkoi.API.Entities.HotelEntity", "Hotel")
                        .WithOne("Search")
                        .HasForeignKey("ZaPutevkoi.API.Entities.HotelFiltersEntity", "HotelEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelImageEntity", b =>
                {
                    b.HasOne("ZaPutevkoi.API.Entities.HotelEntity", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelSectionEntity", b =>
                {
                    b.HasOne("ZaPutevkoi.API.Entities.HotelEntity", "Hotel")
                        .WithMany("Sections")
                        .HasForeignKey("HotelEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Search")
                        .IsRequired();

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ZaPutevkoi.API.Entities.HotelFiltersEntity", b =>
                {
                    b.Navigation("Accommodation")
                        .IsRequired();

                    b.Navigation("Availability");
                });
#pragma warning restore 612, 618
        }
    }
}
